# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KSocketHelperDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KSocketHelperDemo
  pod 'CocoaAsyncSocket'
  target 'KSocketHelperDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KSocketHelperDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
